apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleet-monitor-reports
  namespace: veloshare
  labels:
    app.kubernetes.io/name: fleet-monitor
    app.kubernetes.io/instance: veloshare
    app.kubernetes.io/part-of: veloshare
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
