apiVersion: v1
kind: Service
metadata:
  name: {{ include "veloshare.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "veloshare.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "veloshare.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
