{{- if .Values.global.rbacDemo.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-lister
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "veloshare.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac-demo
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
{{- end }}
