{{- if .Values.global.rbacDemo.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-lister
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "veloshare.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac-demo
{{- end }}
