apiVersion: v1
data:
  ACTIVE_TTL_SECONDS: "7200"
  PRICING_URL: http://pricing.veloshare.svc.cluster.local
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RIDER_URL: http://rider.veloshare.svc.cluster.local
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: veloshare
    meta.helm.sh/release-namespace: veloshare
  creationTimestamp: "2026-08-05T15:33:00Z"
  labels:
    app.kubernetes.io/instance: veloshare
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trip
    app.kubernetes.io/part-of: veloshare
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: trip-0.1.0
  name: trip
  namespace: veloshare
  resourceVersion: "72621"
  uid: a6a01f65-646f-4eb6-8dd1-f2eed272d972
