apiVersion: v1
kind: LimitRange
metadata:
  name: veloshare-limits
  namespace: veloshare
  labels:
    app.kubernetes.io/name: veloshare
    app.kubernetes.io/instance: veloshare
    app.kubernetes.io/part-of: veloshare
spec:
  limits:
  - type: Container
    default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 25m
      memory: 64Mi
    min:
      cpu: 5m
      memory: 16Mi
    max:
      cpu: '2'
      memory: 1Gi
