apiVersion: v1
kind: ResourceQuota
metadata:
  name: veloshare-quota
  namespace: veloshare
  labels:
    app.kubernetes.io/name: veloshare
    app.kubernetes.io/instance: veloshare
    app.kubernetes.io/part-of: veloshare
spec:
  hard:
    requests.cpu: 600m
    requests.memory: 1600Mi
    limits.cpu: '3'
    limits.memory: 3Gi
    pods: '20'
