apiVersion: v1
kind: Service
metadata:
  # Fixed name: reached at http://kibana.veloshare.svc.cluster.local:5601
  name: kibana
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "veloshare.labels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
spec:
  type: ClusterIP
  selector:
    {{- include "veloshare.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
