#!/usr/bin/env python3
"""Split `helm template` output on stdin into the capstone §6.1 k8s/ layout.

Called by scripts/gen-k8s.sh -- see that file for the rationale. Reads the
rendered multi-document YAML on stdin, routes each document to a §6.1
subdirectory by kind, strips Helm-ownership metadata, and writes a
kustomization.yaml for base/ listing what it produced.

Env: OUT (target k8s/ dir), NAMESPACE.
"""
import os
import sys
import pathlib
import yaml

OUT = pathlib.Path(os.environ["OUT"])
NAMESPACE = os.environ.get("NAMESPACE", "veloshare")

# kind -> §6.1 subdirectory. Anything unlisted lands in base/.
ROUTE = {
    "Ingress": "network",
    "NetworkPolicy": "network",
    "ServiceAccount": "security",
    "Role": "security",
    "RoleBinding": "security",
    "ResourceQuota": "quota",
    "LimitRange": "quota",
    "PersistentVolumeClaim": "storage",
}

# Labels Helm injects that must not survive onto a kubectl-managed object.
STRIP_LABELS = {
    "app.kubernetes.io/managed-by",
    "helm.sh/chart",
    "app.kubernetes.io/version",
}

# Deterministic apply order within base/ (kustomize handles deps, but a human
# reading the directory should see the dependency order too).
KIND_ORDER = [
    "Namespace", "ConfigMap", "PersistentVolumeClaim", "Service",
    "StatefulSet", "Deployment", "CronJob", "HorizontalPodAutoscaler",
]


def strip(node):
    """Recursively drop Helm-ownership labels from metadata blocks."""
    if isinstance(node, dict):
        labels = node.get("labels")
        if isinstance(labels, dict):
            for key in STRIP_LABELS:
                labels.pop(key, None)
            if not labels:
                node.pop("labels", None)
        for value in node.values():
            strip(value)
    elif isinstance(node, list):
        for item in node:
            strip(item)
    return node


def slug(kind, name):
    return f"{kind.lower()}-{name}".replace(":", "-")


def main():
    docs = [d for d in yaml.safe_load_all(sys.stdin) if d]

    # Prune before writing, so a resource that the chart no longer renders --
    # or that got renamed, e.g. `pricing` -> `pricing-blue`/`pricing-green`
    # when blue/green landed -- does not survive as an orphan manifest that is
    # tracked in git but referenced by no kustomization.yaml. Every non-
    # kustomization .yaml in these directories is generated by this script, so
    # clearing them is safe; kustomization.yaml itself is rewritten below.
    for sub in ("base", "network", "security", "quota", "storage"):
        d = OUT / sub
        d.mkdir(parents=True, exist_ok=True)
        for stale in d.glob("*.yaml"):
            if stale.name != "kustomization.yaml":
                stale.unlink()

    # The raw path has no `helm --create-namespace`, so it must declare the
    # namespace itself. Helm's chart never renders one.
    ns_doc = {
        "apiVersion": "v1",
        "kind": "Namespace",
        "metadata": {
            "name": NAMESPACE,
            "labels": {"app.kubernetes.io/part-of": "veloshare"},
        },
    }
    docs.insert(0, ns_doc)

    written = {}  # subdir -> list of filenames
    for doc in docs:
        kind = doc.get("kind")
        name = doc.get("metadata", {}).get("name")
        if not kind or not name:
            continue
        strip(doc)
        sub = ROUTE.get(kind, "base")
        fname = f"{slug(kind, name)}.yaml"
        path = OUT / sub / fname
        with path.open("w") as fh:
            yaml.safe_dump(doc, fh, default_flow_style=False, sort_keys=False)
        written.setdefault(sub, []).append((kind, fname))

    header = [
        "# GENERATED by scripts/gen-k8s.sh from helm/veloshare -- do not edit by hand.",
        "# Regenerate after any chart change:  make gen-k8s",
        "apiVersion: kustomize.config.k8s.io/v1beta1",
        "kind: Kustomization",
        f"namespace: {NAMESPACE}",
        "",
        "resources:",
    ]

    # Each §6.1 subdirectory gets its own kustomization, which makes it
    # independently appliable (`kubectl apply -k k8s/network`) AND lets base/
    # pull it in by directory. Kustomize refuses to reference a plain FILE
    # outside the kustomization root, but a directory that is itself a
    # kustomization is fine -- that is the same mechanism the overlays use to
    # reach ../../base.
    for sub in ("network", "security", "quota", "storage"):
        files = sorted(f for _, f in written.get(sub, []))
        if not files:
            continue
        body = header + [f"  - {f}" for f in files]
        (OUT / sub / "kustomization.yaml").write_text("\n".join(body) + "\n")

    # base/kustomization.yaml -- the entry point the overlays build on. It pulls
    # in the sibling §6.1 directories too, so a single `kubectl apply -k
    # k8s/base` brings up the whole platform rather than only the workloads.
    base_files = sorted(
        written.get("base", []),
        key=lambda kf: (KIND_ORDER.index(kf[0]) if kf[0] in KIND_ORDER else 99, kf[1]),
    )
    lines = header + [f"  - {fname}" for _, fname in base_files]
    for sub in ("storage", "quota", "security", "network"):
        if written.get(sub):
            lines.append(f"  - ../{sub}")
    (OUT / "base" / "kustomization.yaml").write_text("\n".join(lines) + "\n")

    total = sum(len(v) for v in written.values())
    for sub in sorted(written):
        print(f"  k8s/{sub}/: {len(written[sub])} manifests")
    print(f"  {total} manifests total")


if __name__ == "__main__":
    main()
