apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "veloshare.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "veloshare.labels" . | nindent 4 }}
data:
  PRICING_UNLOCK_FEE_CENTS: {{ .Values.fare.unlockFeeCents | quote }}
  PRICING_TIER_RATES: {{ .Values.fare.tierRatesJson | quote }}
