apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "veloshare.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "veloshare.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "veloshare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "veloshare.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: pricing
          image: "{{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "veloshare.fullname" . }}
          {{- if (.Values.global.logging).enabled }}
          volumeMounts:
            - name: logs
              mountPath: /var/log/veloshare
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if (.Values.global.logging).enabled }}
        {{- include "veloshare.loggingSidecar" . | nindent 8 }}
        {{- end }}
      {{- if (.Values.global.logging).enabled }}
      volumes:
        {{- include "veloshare.logVolumes" . | nindent 8 }}
      {{- end }}
