apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pricing
  namespace: veloshare
  labels:
    app.kubernetes.io/name: pricing
    app.kubernetes.io/instance: veloshare
    app.kubernetes.io/part-of: veloshare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pricing
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
