apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: veloshare
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: veloshare
    app.kubernetes.io/part-of: veloshare
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: veloshare
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
