apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: veloshare
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: veloshare
    app.kubernetes.io/part-of: veloshare
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: veloshare
  ports:
  - name: http
    port: 80
    targetPort: 8080
