apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "veloshare.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "veloshare.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "veloshare.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - name: fleet-monitor
              image: "{{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.global.image.tag }}"
              imagePullPolicy: {{ .Values.global.image.pullPolicy }}
              env:
                - name: TARGETS
                  value: {{ .Values.targets | quote }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
